In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import missingno as msno
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [11]:
df = pd.read_csv('Churn_Modelling.csv')

In [13]:
df.shape

(10000, 16)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
 14  Unnamed: 14      0 non-null      float64
 15  Unnamed: 15      0 non-null      float64
dtypes: float64(4), int64(9), object(3)
memory usage: 1.2+ MB

In [15]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,0.0,0.0
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700,NaN,NaN
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769,NaN,NaN
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000,NaN,NaN
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000,NaN,NaN
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000,NaN,NaN
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000,NaN,NaN
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000,NaN,NaN

In [17]:
df.head(20)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,NaN,NaN
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,NaN,NaN
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,NaN,NaN
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,NaN,NaN
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,NaN,NaN
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,NaN,NaN
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0,NaN,NaN
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,NaN,NaN
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0,NaN,NaN
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,NaN,NaN
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0,NaN,NaN
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0,NaN,NaN
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0,NaN,NaN
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0,NaN,NaN
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0,NaN,NaN
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0,NaN,NaN
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1,NaN,NaN
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0,NaN,NaN
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0,NaN,NaN
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0,NaN,NaN

In [19]:
df.isnull().sum()

RowNumber              0
CustomerId             0
Surname                0
CreditScore            0
Geography              0
Gender                 0
Age                    0
Tenure                 0
Balance                0
NumOfProducts          0
HasCrCard              0
IsActiveMember         0
EstimatedSalary        0
Exited                 0
Unnamed: 14        10000
Unnamed: 15        10000
dtype: int64

In [22]:
df.dropna()

Empty DataFrame
Columns: [RowNumber, CustomerId, Surname, CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited, Unnamed: 14, Unnamed: 15]
Index: []

In [23]:
df.isnull().sum()

RowNumber              0
CustomerId             0
Surname                0
CreditScore            0
Geography              0
Gender                 0
Age                    0
Tenure                 0
Balance                0
NumOfProducts          0
HasCrCard              0
IsActiveMember         0
EstimatedSalary        0
Exited                 0
Unnamed: 14        10000
Unnamed: 15        10000
dtype: int64

In [24]:
df.head(20)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,NaN,NaN
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,NaN,NaN
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,NaN,NaN
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,NaN,NaN
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,NaN,NaN
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,NaN,NaN
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0,NaN,NaN
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,NaN,NaN
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0,NaN,NaN
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0,NaN,NaN
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0,NaN,NaN
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0,NaN,NaN
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0,NaN,NaN
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0,NaN,NaN
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0,NaN,NaN
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0,NaN,NaN
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1,NaN,NaN
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0,NaN,NaN
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0,NaN,NaN
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0,NaN,NaN

In [26]:
df.drop_duplicates(inplace = True)

In [28]:
df.shape

(10000, 16)

In [29]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,0.0,0.0
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700,NaN,NaN
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769,NaN,NaN
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000,NaN,NaN
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000,NaN,NaN
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000,NaN,NaN
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000,NaN,NaN
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000,NaN,NaN

In [34]:
df = df.sort_values(by = "Geography")

In [36]:
df.head(100)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Unnamed: 14,Unnamed: 15
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,NaN,NaN
3348,3349,15572291,Kao,825,France,Male,40,6,132308.22,1,0,0,117122.50,0,NaN,NaN
7702,7703,15719931,Johnstone,850,France,Male,31,8,0.00,2,1,0,178667.70,0,NaN,NaN
7750,7751,15805162,Sutherland,550,France,Male,25,0,0.00,2,1,1,184221.11,0,NaN,NaN
7755,7756,15680843,Sherrod,675,France,Male,34,8,0.00,2,1,1,184842.21,0,NaN,NaN
7757,7758,15641585,Newton,850,France,Male,40,6,97339.99,1,0,1,88815.25,0,NaN,NaN
7758,7759,15684358,Kang,711,France,Male,41,3,0.00,2,1,1,193747.57,0,NaN,NaN
7762,7763,15808780,Tien,850,France,Female,34,2,0.00,2,0,0,51919.04,0,NaN,NaN
7769,7770,15757473,Chukwujamuike,766,France,Female,27,7,158786.67,2,0,1,47579.25,0,NaN,NaN
7770,7771,15809509,Venables,699,France,Male,29,3,125689.29,1,1,1,151623.71,0,NaN,NaN
7776,7777,15685243,Jamieson,736,France,Female,63,10,0.00,2,0,1,502.70,0,NaN,NaN
7777,7778,15638730,Macleod,711,France,Female,21,0,82844.33,2,0,1,1408.68,0,NaN,NaN
7779,7780,15699225,Pirozzi,757,France,Male,46,0,0.00,2,1,0,37460.05,0,NaN,NaN
7781,7782,15759184,Russell,705,France,Male,34,7,117715.84,1,1,0,2498.67,0,NaN,NaN
7782,7783,15595991,Hsiung,585,France,Male,54,8,87105.32,1,1,1,55346.14,0,NaN,NaN
7783,7784,15681332,Tate,437,France,Female,43,6,0.00,1,1,0,148330.97,1,NaN,NaN
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,NaN,NaN
3346,3347,15726747,Donaldson,714,France,Male,63,4,138082.16,1,0,1,166677.54,0,NaN,NaN
465,466,15726032,Enyinnaya,608,France,Male,33,9,89968.69,1,1,0,68777.26,0,NaN,NaN
2137,2138,15588219,Ford,850,France,Female,38,1,106871.81,2,1,0,29333.01,0,NaN,NaN
2139,2140,15765518,Gregson,643,France,Female,51,2,105229.53,1,1,0,34967.75,1,NaN,NaN
2116,2117,15671609,Ibeabuchi,701,France,Male,44,7,0.00,2,1,0,23425.78,0,NaN,NaN
463,464,15773792,Evans,662,France,Female,32,4,133950.37,1,1,1,48725.68,1,NaN,NaN
2117,2118,15652540,Garnsey,683,France,Male,31,2,0.00,2,0,1,77326.78,0,NaN,NaN
2118,2119,15774857,Synnot,460,France,Female,27,7,0.00,2,1,0,156150.08,1,NaN,NaN
2119,2120,15791836,Wildman,690,France,Male,29,5,0.00,2,1,0,108577.97,0,NaN,NaN
2121,2122,15583576,Tai,671,France,Male,30,2,0.00,1,0,1,102057.86,0,NaN,NaN
7784,7785,15756299,Davis,741,France,Female,64,2,69311.16,1,1,1,59237.72,0,NaN,NaN
2124,2125,15603851,Galkin,704,France,Male,32,7,127785.17,4,0,0,184464.70,1,NaN,NaN
2126,2127,15735719,Babbage,790,France,Female,40,9,0.00,2,1,1,70607.10,0,NaN,NaN
2129,2130,15664881,Norton,702,France,Male,34,4,100054.77,1,1,0,109496.45,0,NaN,NaN
2130,2131,15757568,Bogolyubov,704,France,Female,45,6,0.00,1,1,1,137739.45,0,NaN,NaN
2131,2132,15792660,Gibbons,614,France,Male,38,2,116248.88,1,1,0,105140.92,0,NaN,NaN
2133,2134,15726354,Smith,688,France,Female,32,6,123157.95,1,1,0,172531.23,0,NaN,NaN
2134,2135,15610355,Hunter,713,France,Male,44,1,63438.91,1,1,0,64375.40,0,NaN,NaN
2136,2137,15621893,Bellucci,727,France,Male,18,4,133550.67,1,1,1,46941.41,0,NaN,NaN
2125,2126,15777923,Johnston,544,France,Female,45,6,0.00,2,0,1,151401.33,0,NaN,NaN
2141,2142,15758372,Wallace,674,France,Male,18,7,0.00,2,1,1,55753.12,1,NaN,NaN
7785,7786,15750547,Bair,738,France,Male,26,9,0.00,2,1,1,48644.94,0,NaN,NaN
7790,7791,15607176,Kang,674,France,Male,22,3,0.00,1,1,1,173940.59,0,NaN,NaN
7726,7727,15757617,Lewis,735,France,Male,55,6,134140.68,1,1,0,2267.88,0,NaN,NaN
7745,7746,15701166,Chinedum,660,France,Male,40,5,131754.11,2,1,1,38761.61,0,NaN,NaN
7727,7728,15612729,Chidiebere,681,France,Female,63,7,0.00,2,1,1,55054.48,0,NaN,NaN
7728,7729,15637857,Woolacott,616,France,Female,31,8,0.00,1,0,1,76456.17,0,NaN,NaN
7729,7730,15681007,Yen,850,France,Female,35,2,128548.49,4,1,0,75478.95,1,NaN,NaN
7730,7731,15593622,Service,635,France,Male,43,10,122198.21,2,0,1,179144.54,0,NaN,NaN
7734,7735,15722473,Faulkner,713,France,Male,41,3,0.00,2,1,0,55772.04,0,NaN,NaN
7736,7737,15685640,Dancy,649,France,Female,41,3,130931.83,1,1,1,144808.37,0,NaN,NaN
7737,7738,15566563,Duigan,777,France,Female,30,4,137851.31,1,1,0,5008.23,1,NaN,NaN
7738,7739,15768746,McLean,561,France,Male,33,6,0.00,2,0,0,173680.39,0,NaN,NaN
7741,7742,15634501,Wei,441,France,Male,60,1,140614.15,1,0,1,174381.23,0,NaN,NaN
7744,7745,15806822,Myers,739,France,Female,36,0,0.00,2,0,0,133465.57,0,NaN,NaN
7805,7806,15672499,Iadanza,635,France,Male,34,3,134692.40,2,1,1,83773.02,0,NaN,NaN
7806,7807,15750410,Jordan,680,France,Female,25,4,123816.50,1,1,1,90162.35,0,NaN,NaN
7811,7812,15687852,Vinogradoff,611,France,Male,30,2,104145.65,1,0,0,159629.64,0,NaN,NaN
7724,7725,15673591,Oluchukwu,842,France,Male,44,3,141252.18,4,0,1,128521.16,1,NaN,NaN
7720,7721,15700693,Tu,693,France,Male,68,2,0.00,2,1,1,59864.96,0,NaN,NaN
7718,7719,15670898,McKenzie,740,France,Female,60,5,108028.08,2,0,0,25980.42,1,NaN,NaN
7716,7717,15687540,Obiuto,684,France,Male,32,9,100249.41,2,0,1,67599.69,0,NaN,NaN
7792,7793,15613197,Ugochukwutubelum,590,France,Male,40,8,0.00,2,1,0,62933.03,0,NaN,NaN
7793,7794,15798885,Burns,585,France,Male,56,4,138227.19,2,1,1,55287.84,0,NaN,NaN
7794,7795,15714883,Genovese,508,France,Female,25,2,111395.53,1,0,1,48197.06,0,NaN,NaN
7796,7797,15773949,Cherkasova,692,France,Female,36,3,0.00,2,1,1,8282.22,0,NaN,NaN
7798,7799,15774127,Potter,518,France,Male,46,3,0.00,2,1,0,76515.79,0,NaN,NaN
7801,7802,15798844,Chijindum,678,France,Male,54,7,128914.97,1,0,0,191746.23,1,NaN,NaN
7749,7750,15781619,Stevenson,785,France,Female,38,1,0.00,1,1,0,134964.85,1,NaN,NaN
7787,7788,15675963,Padovano,627,France,Female,57,9,0.00,2,1,1,107712.42,0,NaN,NaN
7747,7748,15628308,Akubundu,850,France,Female,24,6,0.00,2,1,1,13159.90,0,NaN,NaN
7725,7726,15631756,Tuan,482,France,Female,35,5,147813.05,2,0,0,109029.72,0,NaN,NaN
7708,7709,15675650,Duncan,486,France,Female,39,8,97819.36,1,0,1,120531.31,0,NaN,NaN
7710,7711,15754168,McIntosh,506,France,Female,40,3,0.00,1,1,1,144345.58,0,NaN,NaN
7712,7713,15765048,Watt,545,France,Male,30,3,0.00,2,1,0,170307.43,0,NaN,NaN
7713,7714,15786215,Udinese,793,France,Male,56,8,119496.25,2,1,0,29880.99,0,NaN,NaN
7714,7715,15707559,Clark,682,France,Female,30,9,0.00,2,1,1,195104.91,0,NaN,NaN
7715,7716,15582129,Hsia,517,France,Male,62,1,43772.66,3,1,0,187756.24,1,NaN,NaN
7746,7747,15718531,Ukaegbunam,554,France,Female,35,8,0.00,2,1,1,176779.46,0,NaN,NaN
7885,7886,15632344,Jones,792,France,Female,42,0,99045.93,2,1,0,47160.01,0,NaN,NaN
2160,2161,15586821,Bellew,727,France,Male,28,5,0.00,2,0,1,19653.08,0,NaN,NaN
2158,2159,15685706,Bird,731,France,Female,40,7,118991.79,1,1,1,156048.64,0,NaN,NaN
2163,2164,15667554,Cameron,605,France,Male,35,6,0.00,2,1,1,45206.57,0,NaN,NaN
2064,2065,15569503,Yeh,765,France,Male,44,6,0.00,2,1,1,159899.97,0,NaN,NaN
478,479,15677538,Nwokike,569,France,Male,38,7,0.00,1,1,1,108469.20,0,NaN,NaN
2096,2097,15757916,Amaechi,600,France,Female,38,9,0.00,2,1,1,58855.85,0,NaN,NaN
482,483,15750658,Obiuto,798,France,Male,37,8,0.00,3,0,0,110783.28,0,NaN,NaN
481,482,15744398,Burns,525,France,Female,23,5,0.00,2,1,0,160249.10,0,NaN,NaN
2098,2099,15769216,Panicucci,601,France,Female,43,2,0.00,1,1,0,49713.87,1,NaN,NaN
2099,2100,15593295,Greathouse,548,France,Male,57,6,76165.65,1,1,1,133537.53,0,NaN,NaN
2100,2101,15804814,Ts'ui,759,France,Male,40,4,0.00,2,1,0,124615.59,0,NaN,NaN
479,480,15797736,Smith,658,France,Male,29,4,80262.60,1,1,1,20612.82,0,NaN,NaN
477,478,15809722,Ankudinov,611,France,Female,40,8,100812.33,2,1,0,147358.27,0,NaN,NaN
2162,2163,15793842,Krichauff,700,France,Female,34,2,76322.69,1,1,0,128136.29,0,NaN,NaN
2103,2104,15630241,Tretyakova,594,France,Male,61,3,62391.22,1,1,1,192434.11,0,NaN,NaN
2104,2105,15719561,Lin,768,France,Male,42,5,0.00,3,0,0,60686.40,0,NaN,NaN
2105,2106,15615096,Costa,492,France,Female,31,7,0.00,2,1,1,49463.44,0,NaN,NaN
2166,2167,15780650,Biryukov,667,France,Male,40,9,0.00,1,1,1,96670.20,0,NaN,NaN
2237,2238,15639077,Marchesi,622,France,Female,30,2,158584.82,3,1,0,142342.55,1,NaN,NaN
2234,2235,15713655,Calabrese,720,France,Female,38,10,0.00,2,1,1,56229.72,1,NaN,NaN
417,418,15695632,Dellucci,556,France,Female,39,9,89588.35,1,1,1,94898.10,0,NaN,NaN
2244,2245,15756305,Marchesi,515,France,Female,66,6,0.00,2,1,1,160663.11,0,NaN,NaN
2239,2240,15648577,Pickering,493,France,Female,31,3,0.00,1,1,1,176570.28,1,NaN,NaN

In [39]:
df.to_csv("Bank_Customer_Churn_Cleaned.csv", index=False)

In [41]:
df["Geography"].tail(20)

2663    Spain
4743    Spain
4692    Spain
4694    Spain
4696    Spain
4699    Spain
4747    Spain
4700    Spain
4703    Spain
4689    Spain
4708    Spain
4715    Spain
2653    Spain
4723    Spain
4730    Spain
2646    Spain
2642    Spain
2640    Spain
2656    Spain
4999    Spain
Name: Geography, dtype: object

In [46]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [45]:
df.drop(columns=["Unnamed: 14", "Unnamed: 15"], inplace=True)

KeyError: "['Unnamed: 14', 'Unnamed: 15'] not found in axis"

In [47]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [48]:
from sqlalchemy import create_engine

# engine = create_engine(
#     "mysql+pymysql://root:password@localhost/BankAnalytics"
# )

In [50]:
engine = create_engine(
    "mysql+pymysql://root:Sai3336r%40j@localhost/BankAnalytics"
)

In [51]:
connection = engine.connect()
print("Connected Successfully!")
connection.close()

Connected Successfully!

In [52]:
df.to_sql(
    name="bank_customers",
    con=engine,
    if_exists="replace",
    index=False
)

10000